Generalised for hospitalised phenotype
opensafely/post-covid-vaccinated pull request #314
Opened 2022-09-26 08:06 UTC by rdenholm

Also includes estout syntax

2022-09-27 13:49 UTC, venexia requested changes

2022-10-03 09:09 UTC, rdenholm commented on analysis/cox_model.do
>  	gen `var'_tmp = date(`var', "YMD")
Done

2022-10-03 09:21 UTC, rdenholm commented on analysis/cox_model.do
> +* Creating a list of confounders included in covariates_to_fit, currently does not take into account factor variables
Updated

2022-10-03 09:21 UTC, rdenholm commented on analysis/cox_model.do
> +* replacing collapsed covariates in covariates_to_fit (need to see what they look like)
Removed

2022-10-03 09:32 UTC, rdenholm commented on analysis/cox_model.do
> +do "analysis\pseudo_data.do"
Removed

2022-10-03 09:32 UTC, rdenholm commented on analysis/cox_model.do
> +replace cov_cat_deprivation_tmp = 2 if cov_cat_deprivation=="03-Apr"
Updated

2022-10-04 12:46 UTC, venexia approved these changes

2022-10-04 12:46 UTC, merged